services:
  postgres:
    image: postgres:16
    container_name: rentadad-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rentadad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - rentadad_postgres_data:/var/lib/postgresql/data

volumes:
  rentadad_postgres_data:
